version: '3.9'

services:
  comfyui:
    build: .
    container_name: comfy-ui
    ports:
      - "8188:8188"
    volumes:
      # Mount your local folders to the correct paths inside the container
      - ../models:/app/models
      - ../outputs:/app/output
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    